language: python

addons:
  apt:
    packages:
      - gcc  # nds2
      - gfortran  # numpy/scipy
      - libblas-dev  # numpy/scipy
      - liblapack-dev  # numpy/scipy
      - swig  # m2crypto
      - libhdf5-serial-dev

matrix:
  include:
    - python: 2.6
    - python: 2.7
      env: PRE=""
    - python: 3.5
    - python: nightly
    - python: 2.7
      env: PRE="--pre"
  allow_failures:
    - python: 3.5
    - python: nightly
    - python: 2.7
      env: PRE="--pre"

before_install:
  - . .travis/build-nds2.sh
  - pip install -q --upgrade pip
  - pip install ${PRE} -r requirements.txt
  - pip install ${PRE} -q coveralls pytest unittest2

install:
  - pip install .

script:
  - coverage run --source=gwsumm --omit="gwsumm/tests/*,gwsumm/*version*" -m py.test -v gwsumm/
  - coverage run --apend --source=gwsumm --omit="gwsumm/tests/*,gwsumm/*version*" `which gw_summary` --help
  - coverage run --apend --source=gwsumm --omit="gwsumm/tests/*,gwsumm/*version*" `which gw_summary_pipe` --help

after_success:
  - coveralls

cache:
  apt: true
  pip: true
